spring.application.name=service

# Postgres. Reference - compose.yaml file in root service directory
spring.datasource.url=jdbc:postgresql:32768//localhost:/postgres
spring.datasource.username=myuser
spring.datasource.password=secret

# Spring modulith in Vet.java
spring.modulith.republish-outstanding-events-on-restart=false
# To support above property, you need some middleware. You need to store the data somewhere
spring.modulith.events.jdbc.schema-initialization.enabled=true

# logging.level.org.springframework=DEBUG
# logging.level.org.postgresql=DEBUG

spring.ai.openai.api-key=${OPENAI_API_KEY:your-api-key}
spring.ai.openai.chat.options.model=gpt-4o-mini

# For vector store
spring.ai.vectorstore.pgvector.initialize-schema=false

# Virtual threads
spring.threads.virtual.enabled=true